### ISSUE TITLE
Ruby 3.2 support

### ISSUE THREAD

**Issue by yabenatti** [plu/simctl#38]
simctl doesn't work with Ruby 3.2.

Error:

```
NoMethodError: undefined method `=~' for false:FalseClass
.gem/ruby/3.2.0/gems/simctl-1.6.8/lib/simctl/device.rb:30:in `!~'
.gem/ruby/3.2.0/gems/simctl-1.6.8/lib/simctl/device.rb:30:in `available?'
```

The method `=~` was removed on [Ruby 3.2](https://github.com/ruby/ruby/blob/v3_2_0_preview1/NEWS.md)

**Comment by yabenatti** [comment]
Thank you!
